github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/wistia-video-downloader/",
"https://whop.com/serp-downloaders/wistia-video-downloader/"
"https://serp.co/products/wistia-video-downloader/reviews/",
"https://store.serp.co/product-details/product/wistia-video-downloader",
"https://serpdownloaders.github.io/tools/wistia-video-downloader/",
]
